# Vagrantfile for illumos development on OmniOS.

Vagrant.configure(2) do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "omnios-151012"

  config.vm.provider "virtualbox" do |vb|
    # Bump the RAM and CPU to correspond to a proper build VM.
    vb.customize ["modifyvm", :id, "--memory", "4096"]
    vb.customize ["modifyvm", :id, "--cpus", "4"]
  end

  # If true, then any SSH connections made will enable agent forwarding.
  config.ssh.forward_agent = true

  # When provisioning, run the OmniOS-specific setup script automatically.
  config.vm.provision "shell", path: "setup.sh"

  # Mount any other folder you might want inside the VM.
  #config.vm.synced_folder "source/path/", "/destpath/"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"
end
