#!/bin/sh
router=$(/sbin/dhcpinfo 3)
nameservers=$(/sbin/dhcpinfo 6)
domains=$(/sbin/dhcpinfo 15)

# /etc/resolv.conf - overwrites existing file regardless
echo "search ${domains}" > /etc/resolv.conf
for ns in ${nameservers}; do echo "nameserver ${ns}" >> /etc/resolv.conf; done

# default router - unset if any, then set
route delete default >/dev/null 2>&1
route add default ${router}
